aliyun-oss:
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  endpoint: yourEndpoint
captcha:
  img-height: 80
  key-long: 6
casbin:
  model-path: ./resource/rbac_model.conf
email:
  from: xxx@163.com
  host: smtp.163.com
  secret: xxx
  to: xxx@qq.com
excel:
  dir: ./resource/excel/
jwt:
  signing-key: qmPlus
local:
  path: uploads/file
mysql:
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: video_surveillance_go
  log-mode: false
  log-zap: ""
  max-idle-conns: 10
  password: password
  path: 127.0.0.1:3306
  username: root
qiniu:
  img-path: http://qmplusimg.henrongyi.top
system:
  addr: 8888
  db-type: mysql
  oss-type: local
tencent-cos:
  base-url: https://gin.vue.admin
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-key: xxxxxxxx
zap:
  director: log
  encode-level: LowercaseColorLevelEncoder
  format: console
  level: info
  show-line: true
